- .github/workflows/backend-dev-cicd.yml
> 백엔드 개발서버 CI/CD .yml파일 수정

- .github/workflows/backend-dev-cicd.yml
- backend/appspec.yml
- backend/build.gradle
- backend/scripts/deploy.sh
- backend/src/main/resources/application.yml
close: #24 
[issue#24](https://github.com/Da-ily/Da-ily/issues/24)
> dev서버 ci/cd 및 무중단 배포 적용하기

- .github/workflows/create-issue-branch
close: #8
- 이슈 Open시 이슈 번호와 라벨 정보를 바탕으로 브랜치를 생성하는 기능을 만들었습니다.
- 현재는 [🌱 신규 기능] 라벨이 있을 때만 브랜치가 생성됩니다.
- Action의 if: 문법을 이용하면 다른 라벨도 쉽게 추가할 수 있을 것 같습니다.
- 이슈 생성할 때 관련 라벨을 반드시 걸어주셔야 작동합니다!!
- 혹시 깃허브 액션에서 uses로 다른 사람의 액션을 가져다 쓸 때 원본의 workflow yml파일을 볼 수 있는 방법이 있나요?
- 브랜치 생성하는 부분을 action을 가져와서 썼는데, 어떻게 branch를 생성하는지 궁금하네요
- ㅎㅇㅌ
> 이슈 정보에 기반하여 branch 생성

- frontend/package.json
close: #40
styled-components 설치
> chore: styled-components 설치

- .github/workflows/chromatic.yml
> Puranium235 patch 1

- backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
x
- 임시로 작성했던 테스트코드 삭제
- 해당 테스트 코드가 실패해서 ci-cd가 이루어지지 않음
> 임시 테스트코드 삭제

- .github/.idea/.github.iml
- .github/.idea/.gitignore
- .github/.idea/misc.xml
- .github/.idea/modules.xml
- .github/workflows/backend-dev-cicd.yml
- .idea/workspace.xml
- backend/scripts/deploy.sh
- backend/src/main/resources/application.yml
close: #57 
- backend ci 과정에서 build 실패하는 문제 해결
원인
- 컴파일 과정에서 yml파일에 있는 jwt-secret과 jwt-expiration을 불러와야 하는데, yml파일에 해당 정보가 없어서 발생
해결 방법
임의의 jwt-key와 jwt-expiration을 yml파일에 적어 놓겠습니다.
여기서 작성한 jwt값은 실제 서버에서 사용되는 값과 무관합니다.
서버에서는 해당 서버에 있는 yml파일을 주입해서 실행합니다
jar파일을 실행할 때 yml파일을 외부에서 주입하는 것이 가능하더라구요
관련된 내용으로 배포 스크립트를 조금 수정했습니다.
> backend ci 과정에서 build 실패하는 문제 해결

- .github/ISSUE_TEMPLATE/refactor.yml
- .github/issue-branch.yml
- .idea/.gitignore
- .idea/Da-ily.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
close: #55 
- refactor imoji가 깨져서 수정
> 라벨에서 refactor emoji 수정

- .github/workflows/backend-dev-cicd.yml
close: #65 
- 깃허브 액션에서 submoudle을 사용하도록 수정
> 깃허브 액션에서 submoudle을 사용하도록 수정

- .github/workflows/backend-dev-cicd.yml
- backend/build.gradle
- backend/src/main/java/com/daily/daily/oauth/controller/OauthController.java
- backend/src/main/java/com/daily/daily/oauth/provider/KakaoUserInfo.java
- backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
- backend/src/test/java/com/daily/daily/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/daily/daily/auth/jwt/JwtUtilTest.java
- backend/src/test/java/com/daily/daily/auth/service/AuthServiceTest.java
- backend/src/test/java/com/daily/daily/oauth/controller/OauthControllerTest.java
close: #69
- Auth, OAuth 테스트 코드 작성
- 작성하는데 며칠이 걸렸는데 테스트 코드 작성해본 경험이 많이 없어서 미흡한 결과물이 나온 것 같습니다. 프로젝트 계속 작업하면서 채워가도록 하겠습니다.
> Auth, OAuth 패키지 테스트 코드 작성

- frontend/.eslintrc.json
close: #
* import 문에 확장자명 (".js", ".jsx") 을 명시 하지 않아도 되도록, ESLint config 수정
> feat:ESLint import 관련 plugin, setting 추가

- backend/src/main/java/com/daily/daily/member/service/MemberService.java
- backend/src/main/java/com/daily/daily/member/validator/NicknameValidator.java
- backend/src/main/java/com/daily/daily/oauth/OAuth2CustomUser.java
- backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
- backend/src/main/java/com/daily/daily/oauth/constant/SocialType.java
- backend/src/main/java/com/daily/daily/oauth/controller/OauthController.java
- backend/src/main/java/com/daily/daily/oauth/handler/OAuth2FailureHandler.java
- backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
- backend/src/main/java/com/daily/daily/oauth/provider/GoogleUserInfo.java
- backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
> oAuth, member 코드 리팩토링

- backend/src/main/java/com/daily/daily/member/service/MemberService.java
- backend/src/main/java/com/daily/daily/member/service/NicknameGenerator.java
- backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
- backend/src/main/java/com/daily/daily/oauth/provider/KakaoUserInfo.java
- backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
- backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
close: #81
- 닉네임 없이 회원가입을 진행할 경우 랜덤 닉네임을 부여합니다.
> 회원가입시 닉네임 부여 기능 구현

- backend/build.gradle
- backend/src/main/java/com/daily/daily/common/dto/ExceptionResponseDTO.java
- backend/src/main/resources/static/docs/api-document.html
close: #97
[이슈 참고](https://github.com/Da-ily/Da-ily/issues/97)
ExceptionResponseDTO 필드 쪼끔 바꿨습니다.
-> isSuccessful =false 필드 추가
아 제발 빌드되라..
> submodule 파일이 복사가 안되는 문제 해결

- frontend/src/App.js
- frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
- frontend/src/constants/routes.js
- frontend/src/pages/LoginPage/FindIdPage.jsx
- frontend/src/pages/LoginPage/SentId.jsx
- frontend/src/pages/LoginPage/SentPassword.jsx
- frontend/src/pages/RegisterPage/RegisterDone.jsx
- frontend/src/pages/RegisterPage/RegisterDonePage.jsx
- frontend/src/pages/RegisterPage/RegisterPage.jsx
- frontend/src/pages/RegisterPage/RegisterPage.styled.jsx
close: #82
왼쪽에 네비게이션 없는 페이지 레이아웃 구분
회원가입, 회원가입 완료, 아이디찾기, 아이디 전송완료, 비밀번호 전송완료 페이지 작성
아직 버튼끼리 이어져있지는 않습니다.
~~완료 페이지들은 라우팅이 아니라 한 페이지 내에서 상태를 이용해서 이동하고 싶어서 url에 연결되어 있지 않습니다.
> 로그인, 회원가입 페이지 디자인

- backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
> SecurityConfig cors disable 및 default success url 설정 .java

- backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
- backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
close: #110 
- CorsFilter가 아닌 CorsConfigurationSource를 이용해서 cors 설정
> cors 세팅 변경

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
- backend/src/main/java/com/daily/daily/auth/service/TokenService.java
- backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
close: #105 
밀고 새로 받아서 올리려는데 또 오류가 떠서 시간이 좀 걸렸네요. 암튼 해결~
> 인증 & 인가 API restdocs 작성

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
- backend/src/main/java/com/daily/daily/auth/service/TokenService.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
> api-document 파일 업데이트

- backend/build.gradle
- backend/src/main/java/com/daily/daily/dailrypage/DailryPageExceptionHandler.java
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/exception/DailryPageNotFoundException.java
- backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
close: #129 
- 페이지 생성 기능 구현
- 페이지 수정 기능 구현
- 페이지 조회 기능 구현
- 페이지 삭제 기능 구현
- 일단 간단한 샘플용으로 만들었고, 그대로 사용하기엔 조금 신경 써야 할 것이 몇 가지 있어서 Restdocs랑 테스트 작성은 아직 안했습니다.
- 신경 써야 할 것들
- 연관 관계매핑 
- 최적화 요소들
- 어제 좀 휘갈겨 작성했던 코드를 좀 가다듬은 정도..? 입니다
> 다일리 페이지 관련 기능 구현

- frontend/package.json
- frontend/src/apis/customAxios.js
- frontend/src/apis/memberApi.js
- frontend/src/components/common/Input/Input.jsx
- frontend/src/hooks/useForm.jsx
- frontend/src/hooks/useJoinForm.jsx
- frontend/src/pages/JoinPage/JoinForm.jsx
- frontend/src/pages/JoinPage/JoinPage.styled.jsx
close: #126
- useForm 커스텀 훅 에 formik 라이브러리 추가
- formik options 추가
- useJoinForm 커스텀 훅 생성
- formik 으로 관리하는 form 상태 외, 유효성 검증에 필요한 상태 관리
- JoinForm 페이지 에 적용
- 에러 / 유효 알려주는 텍스트 컴포넌트 생성
> formik 라이브러리 도입 및 form 유효성 검증 기능 추가

- frontend/.gitignore
- frontend/package.json
close: #131 
- certificate 파일 추가
- package.json script 추가
> localhost https 사용 설정 추가

- .github/workflows/create-issue-branch.yml
- backend/scripts/deploy.sh
close: #138 
1. 배포스크립트 수정
-  jar파일 실행 후 sleep하는 시간 20 -> 30 변경
2. 이제 ✨ 리팩터링 라벨이 붙어있으면 이슈 브랜치가 생성됩니다.
- ex ) "refactor/be/#이슈넘버"
1, 2번 둘 다 간단한 것들이라 그냥 이슈 하나에 묶어서 했습니다.
> 배포스크립트 수정 / ✨ 리팩터링 라벨 붙어도, 이슈 브랜치 생성

- backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
> JwtAuthorizationFilter 코드 수정

- backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
- backend/src/main/java/com/daily/daily/auth/exception/TokenExpiredException.java
- backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
- backend/src/main/java/com/daily/daily/auth/service/AuthService.java
- backend/src/main/java/com/daily/daily/auth/service/TokenService.java
close: #141
-  token 재발급시 만료시간 검증
-  token 재발급시 body x. cookie로 응답값
-  로그아웃시 cookie에 있는 token 삭제
블랙리스트나 추가 redis 관련 작업은 새로 이슈를 만들어서 작업하겠습니다.
> 토큰 관련 수정 작업

- .github/workflows/backend-dev-cicd.yml
- backend/build.gradle
- backend/src/main/java/com/daily/daily/common/GlobalExceptionHandler.java
- backend/src/main/java/com/daily/daily/common/config/S3Config.java
- backend/src/main/java/com/daily/daily/common/domain/BaseTimeEntity.java
- backend/src/main/java/com/daily/daily/common/exception/FileContentTypeUnmatchedException.java
- backend/src/main/java/com/daily/daily/common/exception/FileUploadFailureException.java
- backend/src/main/java/com/daily/daily/common/service/S3StorageService.java
- backend/src/main/java/com/daily/daily/post/controller/PostController.java
- backend/src/main/java/com/daily/daily/post/domain/Post.java
- backend/src/main/java/com/daily/daily/post/dto/PostCreateDTO.java
- backend/src/main/java/com/daily/daily/post/dto/PostResponseDTO.java
- backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
- backend/src/main/java/com/daily/daily/post/service/PostService.java
- backend/src/test/java/com/daily/daily/common/service/S3StorageServiceTest.java
- backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
- backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
- backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
close: #148 
- 커뮤니티 글 생성 기능 구현
- S3 저장소에 파일 이름을 어떠한 방식으로 저장 해야 할지 고민입니다.
- 일단 지금은 UUID를 PREFIX로 붙여서 저장했습니다.
- 한 번에 모아서 PR하는 것이 안 좋은 습관 같아서 나눠서 작업했습니다.
- 그리고 PR을 오래동안 안 하니 뭔가 텐션이 떨어지는 느낌..
> 커뮤니티 글 생성 기능 구현

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/dailry/controller/DailryController.java
- backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
- backend/src/main/java/com/daily/daily/dailry/dto/DailryDTO.java
- backend/src/main/java/com/daily/daily/dailry/dto/DailryUpdateDTO.java
- backend/src/main/java/com/daily/daily/dailry/exception/DialryNotFoundException.java
- backend/src/main/java/com/daily/daily/dailry/repository/DailryRepository.java
- backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
- backend/src/main/java/com/daily/daily/member/domain/Member.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
- backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
close: #146
-  MEMBER <-> DAILRY 맵핑
-  다일리 생성
-  다일리 수정
-  다일리 조회
-  다일리 삭제
-  DAILRY <-> DAILRY_PAGE 맵핑
-  RestDocs 문서 작성
오류의 세계는 끝이 없네요..
> 다일리, 다일리 페이지 관련 기능 구현하기

- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
close: #173 
[이슈 참고] (https://github.com/dailry/dailry/issues/173)
Hibernate Utils를 써서 했는데,,,,, 내부적으로 쿼리가 어떻게 나가는지 모르겠음.
> 다일리 페이지 수정로직 변경

- backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
close: #178 
- 토큰 검증에서 문제가 발생할 경우 에러 응답이 작성되지 않는 문제 해결
- 필터를 안 걸면 된다!!
> 토큰 검증에서 문제가 발생할 경우 에러 응답이 작성되지 않는 문제 해결

- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
close: #186 
- 페이지 수정 API 요청 포맷 변경 및 Validation 추가
> 페이지 수정 API 요청 포맷 변경 및 Validation 추가

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/dailry/controller/DailryController.java
- backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
- backend/src/main/java/com/daily/daily/dailry/dto/DailryFindDTO.java
- backend/src/main/java/com/daily/daily/dailry/exception/DailryNotFoundException.java
- backend/src/main/java/com/daily/daily/dailry/repository/DailryRepository.java
- backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageFindDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
close: #180
- 다일리 전체 리스트 조회
-  다일리페이지 전체 리스트 조회
-  pageNumber 추가
-  restdocs 작성
> 다일리, 다일리페이지 전체 리스트 조회

- frontend/src/components/decorate/TextBox/TextBox.jsx
- frontend/src/components/decorate/TextBox/TextBox.styled.jsx
close: #188 
- 내부 텍스트 에 따라 높이가 자동 변환되게 끔 구현
- 줄어들 때, 제대로 작동하지 않는 이슈(행 하나가 줄어들 때 한줄이 바로 사라지지 않는) 가 있어 이후 추가 구현 필요
> 텍스트 박스 꾸미기 컴포넌트 추가

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/post/controller/PostController.java
- backend/src/main/java/com/daily/daily/post/domain/Post.java
- backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
- backend/src/main/java/com/daily/daily/post/dto/PostReadSliceResponseDTO.java
- backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
- backend/src/main/java/com/daily/daily/post/service/PostService.java
- backend/src/main/java/com/daily/daily/postcomment/dto/PostCommentSliceDTO.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
- backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
- backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
close: #194 
- 게시글 조회 (무한스크롤) 기능 구현
- 게시글 관련 API들 restdocs 작성하기
- 좋아요 갯수를 어떻게 불러와야 할지 고민입니다.
- 한방 쿼리로 좋아요 갯수를 Count할 깔끔한 방법이 딱히 생각이 나지 않아서 일단 현재는 N+1쿼리인 상태입니다.
> 게시글 조회 (무한스크롤) 기능 구현 및 Restdocs

- backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
- backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
- backend/src/main/resources/static/docs/api-document.html
close: #171 
- 다일리 수정 소유권 검사
-  다일리 삭제 소유권 검사
-  다일리 조회 소유권 검사
-  다일리 페이지 수정 소유권 검사
-  다일리 페이지 삭제 소유권 검사
-  다일리 페이지 조회 소유권 검사
> 다일리, 다일리 페이지 소유권 검사 로직 구현

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPagePreviewDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageThumbnailDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
- backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
- backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
close: #198 
- DailryPageController 테스트 코드 작성
- restdocs 작성
- 최대한 Main코드 안 건들고 테스트 코드만 작성 하려고 했는데 몇 군데 수정한 곳이 있습니다.
- DailryPageCreateResponseDTO 를 따로 만들어서 다일리 생성할 때에는 해당 DTO 객체를 반환해 주었습니다.
- elements가 null이니까 테스트코드 작성이 잘 안되더라구요. 
- 그리고 페이지 생성할 때는 elements가 항상 null이라서, 굳이 반환하지 않는 것이 낫다고 판단했습니다.
```java
public class DailryPageCreateResponseDTO {
private Long dailryPageId;
private String background;
private Long pageNumber;
public static DailryPageCreateResponseDTO from(DailryPage dailryPage) {
return DailryPageCreateResponseDTO.builder()
.dailryPageId(dailryPage.getId())
.background(dailryPage.getBackground())
.build();
}
}
```
- 페이지 목록 미리보기 API 반환으로 DailryPagePreviewDTO 를사용했습니다.
```java
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class DailryPagePreviewDTO {
private Long …
```
> DailryPageController 테스트 코드 작성 및 restdocs 작성

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
- backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
- backend/src/main/java/com/daily/daily/dailrypage/exception/DailryPageThumbnailNotFoundException.java
- backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
- backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
close: #200
- 섬네일 저장 기능 구현
- 다일리 페이지 수정 테스트 코드 수정
- 다일리 페이지 수정 restdocs 작성
건우님 작업물로 덮으려고 하다가 백업이 잘못돼서 처음부터 다시 작업했네요..ㅎ
> 섬네일 저장 기능 구현

- frontend/src/components/common/Hamburger/DailryHamburger.jsx
close: #221 
이벤트 핸들러에 `stopPropagation`을 추가했습니다
> 네비게이션 버그 수정

- .github/workflows/backend-dev-cicd.yml
- .github/workflows/backend-prod-cicd.yml
- backend/DockerFile-Prod
close: #239 
backend-prod-cicd 워크플로우 파일 수정
> backend-prod-cicd.yml 수정

- .github/workflows/backend-prod-cicd.yml
- backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
- backend/src/main/java/com/daily/daily/auth/dto/CookieDTO.java
- backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
- backend/src/main/java/com/daily/daily/auth/service/AuthService.java
- backend/src/main/java/com/daily/daily/auth/service/TokenService.java
- backend/src/main/java/com/daily/daily/common/service/CookieService.java
- backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
- backend/src/test/java/com/daily/daily/integration/auth/jwt/JwtUtilTest.java
close: #242
- 로그아웃 기능 수정
- 쿠키 관련 작업을 한 군데에서 하도록 하기
도메인 문제인걸 모르고 이상한 삽질할뻔했네요. 이제 로그아웃하면 cookie가 지워져서 회원정보 get 해도 403 에러가 뜹니다.
> 쿠키 관련 기능 작업하기

- backend/src/main/java/com/daily/daily/dailry/DailryExceptionHandler.java
close: #251 
- DailryNotFoundException 익셉션 핸들러로 처리하기
handler 만들어서 작업했는데 재거 제대로 이해한게 맞을까요..?
> DailryNotFoundException 익셉션 핸들러로 처리하기

- backend/src/main/java/com/daily/daily/member/domain/Member.java
- backend/src/main/java/com/daily/daily/post/PostExceptionHandler.java
- backend/src/main/java/com/daily/daily/post/controller/PostLikeController.java
- backend/src/main/java/com/daily/daily/post/domain/Post.java
- backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
- backend/src/main/java/com/daily/daily/post/exception/NotPreviouslyLikedException.java
- backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
- backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydsl.java
- backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
- backend/src/main/java/com/daily/daily/post/service/PostLikeFacade.java
- backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
- backend/src/main/java/com/daily/daily/post/service/PostService.java
- backend/src/main/resources/db/migration/V202402281407__addLikeCount.sql
- backend/src/main/resources/db/migration/V202403011442__addVersionToPost.sql
- backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
- backend/src/test/java/com/daily/daily/post/service/PostLikeServiceConcurrencyTest.java
- backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java
- backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
- backend/src/test/java/com/daily/daily/testutil/config/JpaTest.java
- backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java
- backend/src/test/java/com/daily/daily/testutil/generator/MemberGenerator.java
- backend/src/test/java/com/daily/daily/testutil/generator/PostGenerator.java
- backend/src/test/resources/application.yml
close: #250 
[이슈 참고](https://github.com/dailry/dailry/issues/250)
낙관적 락 예외 이후에 재시도를 보내는 과정 때문에 어플리케이션 코드가 좀 복잡해진 것 같은데요.
이 문제는 스프링 AOP를 이용하면 해결할 수 있을 것 같습니다.
그런데 이게 좀 알아보니 어려워서...ㅠㅠ 공부 좀 해 본 다음에 리팩토링 해볼게요
이번 PR에 관한 내용은 추후에 위키에 올리겠습니다!
- 테스트 환경에서 적용될 .yml파일을 추가했습니다.
> 좋아요 기능 리팩토링 (반정규화, 동시성 문제 해소)

- frontend/src/apis/customAxios.js
close: #
* 환경변수가 production 일 때, uri 다르게 적용되도록 수정
> 환경변수가 production 일 때, uri 다르게 적용되도록 수정

- frontend/src/apis/customAxios.js
> customAxios header에서 Authorization 삭제

- frontend/src/apis/customAxios.js
- frontend/src/constants/api.js
- frontend/src/pages/LoginPage/LoginPage.jsx
* 소셜로그인 링크 수정
* vercel 에 지정한 환경변수가 production, preview 배포 된 도메인에 따라 다르게 Api uri 로 적용되도록 수정 ( 확인 필요 )
> 소셜로그인 링크 수정 및 API URI 환경변수로 지정

- frontend/src/components/common/Tooltip/Tooltip.jsx
- frontend/src/components/common/Tooltip/Tooltip.styled.jsx
- frontend/src/constants/toolbar.js
- frontend/src/pages/DailryPage/DailryPage.jsx
- frontend/src/pages/HomePage/HomePage.jsx
- frontend/src/pages/HomePage/HomePage.styled.jsx
- frontend/src/styles/color.js
issue 313
- 홈 페이지 에 마이페이지 버튼 추가
- 스티커 꾸미기 컴포넌트 임시 주석 처리
- 다일리 페이지 에 공유하기 버튼 추가
-  다일리 페이지 툴바 버튼 hover 시 해당 버튼이 어떤 기능을 하는지 알려주는 툴팁 추가
- Tooltip 컴포넌트 추가
- 다일리 페이지 툴바 버튼 텍스트, 툴팁 텍스트 관련 상수화
- `PAGE_TOOL_TYPE`, 
- `DECORATE_TOOLS_TOOLTIP`, `PAGE_TOOLS_TOOLTIP`
> ver.0 Frontend 개선 일부 작업

- backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
- backend/src/main/java/com/daily/daily/auth/jwt/RefreshToken.java
close: #320
- 액세스 토큰 만료 시 재발급 받도록 함
- Redis TTL 수정
- 코드 리팩토링
> 버그 수정 및 리팩토링

- backend/src/docs/asciidoc/api-document.adoc
- backend/src/main/java/com/daily/daily/post/controller/PostLikeController.java
- backend/src/main/java/com/daily/daily/post/domain/PostLike.java
- backend/src/main/java/com/daily/daily/post/repository/PostLikeRepository.java
- backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
- backend/src/main/resources/static/docs/api-document.html
- backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
- backend/src/test/java/com/daily/daily/post/fixture/PostLikeFixture.java
- backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java
close: #327 
- 유저가 좋아요를 눌렀는지 여부를 확인하는 API 개발
- 프론트에서 게시글Id 목록을 보내면, TRUE FALSE 형식으로 반환함.
> 유저가 좋아요 눌렀는지 여부를 확인하는 API 개발

- .github/workflows/sync-to-forked-repository.yml
> remote 와 fork repository synchronize 자동화 workflow 추가
