dailry/dailry

backend/build.gradle
backend/src/main/java/com/daily/daily/common/dto/ExceptionResponseDTO.java
backend/src/main/java/com/daily/daily/member/constant/MemberRole.java
backend/src/main/java/com/daily/daily/member/controller/MemberController.java
backend/src/main/java/com/daily/daily/member/domain/Member.java
backend/src/main/java/com/daily/daily/member/dto/JoinDTO.java
backend/src/main/java/com/daily/daily/member/dto/MemberInfoDTO.java
backend/src/main/java/com/daily/daily/member/dto/NicknameDTO.java
backend/src/main/java/com/daily/daily/member/dto/PasswordUpdateDTO.java
backend/src/main/java/com/daily/daily/member/validator/NicknameValidator.java
backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
backend/src/test/java/com/daily/daily/member/repository/MemberRepositoryTest.java
backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
backend/src/test/java/com/daily/daily/member/validator/NicknameValidatorTest.java

close: #67 
- MemberRole을 다음과 같이 정리 (Security 기본 권한문제)
```java
public enum MemberRole {
ROLE_MEMBER, ROLE_ADMIN
}
```
- Member 도메인 안에서 MemberRole 값을 필드에서 셋팅하는것을 삭제했습니다. (깃허브 액션에서 자꾸 에러로그로떠서)
- 컨트롤러 계층의 테스트를 꼬박꼬박 다 작성하는 것이 맞는지 모르겠네요
- 생산성이 너무 떨어진다는 느낌을 받았습니다. 
ㅎㅇㅌ.......!!!!

Member패키지 테스트코드 작성

---

backend/build.gradle
backend/src/docs/asciidoc/api-document.adoc
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
backend/src/test/java/com/daily/daily/testutil/document/RestDocsUtil.java
backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcConstant.java
backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcTest.java
backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcUtil.java
backend/src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
backend/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet

close: #93 
- MemberController 파트를 RestDocs로 문서화 했습니다.
- 로그인 로그아웃은 Refresh토큰을 도입하면 다시 API문서가 변경되어야 할 것 같아서 안 했습니다.
- 테스트코드 작성용 util 클래스를 만들었습니다.. 
- RestDocsUtil 클래스를 만들었습니다.
- MockMvcConstant, MockMvcTest, MockMvcUtil 등을 만들었는데 MockMvcTest와 MockMvcUtil 는 만들다가 썩 마음에 들지 않아서 사용하지 않고 있습니다. 중복 코드를 조금 제거하려는 목적으로 만들었는데, 추후에 조금 더 만져보고 별다른 수확이 없으면 지우겠습니다.
- 위키에 Restdocs 사용법을 올렸습니다. 나중에 문서화 할 때 참고해 주세요
- restdocs 관련된 몇 가지 이슈도 위키에 같이 정리해서 올렸습니다.
- 새해복 많이받으세요 ㅎㅇㅌ

Spring Restdocs를 이용한 API 문서화

---

backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java

close: #118 
- defaultSuccessfulURL 제거
- OAuth2SuccessHandler 에서 소셜로그인 성공시 http://localhost:3000로 리다이렉트 하도록 설정
괜히 붙여서 고생했네요.. 이렇게 예상치 못하게 동작할 줄은..

defaultSuccessfulURL 제거

---

backend/src/docs/asciidoc/api-document.adoc
backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
backend/src/test/java/com/daily/daily/integration/auth/jwt/JwtUtilTest.java

close: #124 
- 로그인 성공시 토큰을 쿠키로 전달하도록 변경하였습니다. 
(이유 및 자세한 내용은 Discord의 소셜로그인 쓰레드를 참고해주세요)
- 이전에는 로그인 성공시 토큰을 헤더로 줬었어서, 토큰을 헤더에 넣어주는 메서드들을 제거했습니다.
- JwtUtil클래스 리팩토링도 조금 했습니다.
ㅎㅇㅌ

로그인 성공시 토큰을 쿠키로 전달

---

backend/src/docs/asciidoc/api-document.adoc
backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
backend/src/main/java/com/daily/daily/member/controller/MemberController.java
backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
backend/src/test/java/com/daily/daily/integration/auth/jwt/JwtUtilTest.java
backend/src/test/java/com/daily/daily/integration/oauth/controller/OauthControllerTest.java
backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java

close: #132
- 엔드포인트 members로 변경하기
- 관련 Restdocs 수정
-  AuthorizationFilter에서 request의 cookie에 접근해서 토큰을 검증하도록 변경
- 관련 Restdocs 수정
accessToken 재발급 과정도 cookie로 처리할 수 있도록 수정했습니다.

코드 수정 및 Restdocs 수정 작업

---

frontend/.eslintrc.json
frontend/package.json
frontend/src/components/da-ily/Moveable/Moveable.jsx
frontend/src/components/decorate/Drawing/Drawing.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #163 
- ref 배열에 각 꾸미기 컴포넌트 ref 를 삽입하여, 클릭할시 해당 ref 를 Movable 컴포넌트가 가리키도록 수정
- 관련 이벤트 핸들러 쉽게 등록할 수 있는 moveable-helper 추가

Moveable 컴포넌트 선택 방식 수정

---

frontend/.eslintrc.json
frontend/src/components/da-ily/Moveable/Moveable.jsx
frontend/src/hooks/useCreateDecorateComponent.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #154 
- useCreateDecorateComponent 커스텀 훅 생성
- 페이지 를 클릭하면 해당위치에 꾸미기 컴포넌트 생성 
- 꾸미기 컴포넌트 들이 담겨있는 배열에 삽입/삭제 하는 방식으로 구현.
- `jsx-a11y/no-static-element-interactions` 규칙 제거
- 서비스 특성상, 일반 엘리멘트에 상호작용가능한 이벤트를 부착해야 하기때문에 제거.
- 페이지 를 클릭하면 컴포넌트가 생성된다는 것을 알려줄 UI/UX 가 필요할 듯 합니다.
- type 에 맞는 컴포넌트를 어떤 방식으로 저장하고 맵핑 할지, 고민해 보면 좋을 듯 합니다.
- 새로운 꾸미기 컴포넌트 데이터를 생성하는 로직은 아직 미구현. 툴바가 완성되면 해당 기능 구현 예정.

꾸미기 컴포넌트 생성

---

frontend/src/hooks/useCreateDecorateComponent.jsx
frontend/src/pages/DailryPage/DailryPage.jsx
frontend/src/pages/DailryPage/DailryPage.styled.jsx

close: #169 
- 꾸미기 컴포넌트 생성 위치 를 지정하는 방식 수정
- 마우스가 클릭되는 절대 위치 값에서, 부모 컨테이너 의 위치를 고려해 상대 위치 값으로 수정 (부모 요소 (컨테이너) Reference 의 `getBoundingClientRect`().`left` 값 - 현재 마우스 가 클릭된 위치)
- 부모 컨테이너 `overflow` : `hidden` 값 추가 
- 꾸미기 컴포넌트 가 부모 컨테이너 영역을 벗어날 때, 가려지도록 조치
- 꾸미기 컴포넌트 가 부모 컨테이너 영역을 벗어날 때, 어떻게 할지

꾸미기 컴포넌트 생성 위치 계산 로직 수정

---

backend/src/docs/asciidoc/api-document.adoc
backend/src/main/java/com/daily/daily/post/controller/PostController.java
backend/src/main/java/com/daily/daily/post/domain/Hashtag.java
backend/src/main/java/com/daily/daily/post/domain/Post.java
backend/src/main/java/com/daily/daily/post/domain/PostHashtag.java
backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
backend/src/main/java/com/daily/daily/post/dto/PostRequestDTO.java
backend/src/main/java/com/daily/daily/post/dto/PostWriteRequestDTO.java
backend/src/main/java/com/daily/daily/post/dto/PostWriteResponseDTO.java
backend/src/main/java/com/daily/daily/post/repository/HashtagRepository.java
backend/src/main/java/com/daily/daily/post/repository/PostHashtagRepository.java
backend/src/main/java/com/daily/daily/post/service/HashtagService.java
backend/src/main/java/com/daily/daily/post/service/PostService.java
backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
backend/src/test/java/com/daily/daily/post/service/HashtagServiceTest.java
backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java

close: #189 
- 게시글 업로드시 해시태그를 붙일 수 있다.
- 게시글의 해시태그를 수정할 수 있다.
- 게시글의 해시태그를 삭제할 수 있다.
- 게시글 조회시 해시태그를 같이 조회할 수 있다.
- JPA 양방향 연관관계를 적용하면서 삽질을 좀 많이 해서 늦었네요.. 관련해서 위키에 작성할게요
- 해시태그 수정 로직은, 우선은 delete로 싹 지우고 추가하는 방식으로 했습니다. 대신 최적화 할 수 있는 방안에 대해서 주석을 조금 남겼습니다.

게시글에 해시태그 기능 추가 

---

backend/build.gradle
backend/src/main/java/com/daily/daily/common/config/QuerydslConfig.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
backend/src/main/java/com/daily/daily/member/domain/Member.java
backend/src/main/java/com/daily/daily/post/repository/PostHashtagRepository.java
backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydsl.java
backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
backend/src/main/java/com/daily/daily/post/service/PostService.java
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
backend/src/test/java/com/daily/daily/member/repository/MemberRepositoryTest.java
backend/src/test/java/com/daily/daily/post/repository/PostLikeRepositoryTest.java
backend/src/test/java/com/daily/daily/postcomment/repository/PostCommentRepositoryTest.java

close: #202 
- 게시글 조회시 N+1쿼리 해결
- submodule의 yml 파일 업데이트
-  default_batch_fetch_size: 200 으로 설정했습니다. 
-  JPA에서 일대다 관계에서 N+1문제를 해결하기 위해서 해당 설정(BatchSize)을 사용한다고 하네요
-  jpa naming strategy를 업데이트 했습니다.
- org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy 
- 엔티티 네이밍에서 Camel 규칙에 해당하는 부분을 Underscore로 치환해줍니다.
- ex) createdTime -> created_time
- 로컬에서 테이블 한 번 다 날리고 작업하시는 것을 추천드립니다.
- Querydsl 의존성을 추가했습니다.
- p6spy 의존성을 추가했습니다.
- sql에서 ? 로 뜨는 바인딩 파라미터를 실제 값으로 대체해줍니다.
- 개발 단계에서 사용하기 좋은 것 같습니다. 실제 나가는 쿼리를 볼 수가 있습니다.
- 운영 단계에서는 빼는 것이 좋아 보입니다. (성능문제)

좋아요 갯수 최적화하기

---

backend/src/main/java/com/daily/daily/DaIlyApplication.java
backend/src/main/java/com/daily/daily/common/config/JPAConfig.java
backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
backend/src/test/java/com/daily/daily/postcomment/controller/PostCommentControllerTest.java
backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcTest.java

close: #208 
- `JPAConfig` 에서 `@EnableJpaAuditing` 설정하기. 
- `@EnableJpaAuditing` 은 저희 프로젝트에서 `BaseTimeEntity` 와 관련된 설정
- 컨트롤러 테스트에서 `@MockBean(JpaMetamodelMappingContext.class)` 제거
참고 자료
https://giron.tistory.com/127

테스트 코드에서 @MockBean(JpaMetamodelMappingContext.class) 제거

---

backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
backend/src/main/java/com/daily/daily/member/domain/Member.java
backend/src/main/java/com/daily/daily/post/domain/Hashtag.java
backend/src/main/java/com/daily/daily/post/domain/Post.java
backend/src/main/java/com/daily/daily/post/domain/PostHashtag.java
backend/src/main/java/com/daily/daily/post/domain/PostLike.java
backend/src/main/java/com/daily/daily/postcomment/domain/PostComment.java
backend/src/main/java/com/daily/daily/postcomment/service/PostCommentService.java
backend/src/test/java/com/daily/daily/dailry/fixture/DailryFixture.java
backend/src/test/java/com/daily/daily/member/fixture/MemberFixture.java
backend/src/test/java/com/daily/daily/member/service/MemberEmailServiceTest.java
backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
backend/src/test/java/com/daily/daily/postcomment/fixture/PostCommentFixture.java
backend/src/test/java/com/daily/daily/postcomment/service/PostCommentServiceTest.java

close: #210 
- 엔티티 클래스에서 `@AllArgsConstructor`를 제거하였습니다.
- 이제 엔티티를 생성할 때 `id`값을 할당할 수 없습니다.
- `@AllArgsConstructor`를 제거하니 `id`를 활용한 테스트 코드에서 문제가 생겼습니다.
- 찾아보니 스프링 테스트 유틸 중에 `ReflectionTestUtils` 를 사용하면 private 필드에도 접근해서 값을 부여할 수가 있었습니다.
- ex : `ReflectionTestUtils.setField(댓글, "id", COMMENT_ID);` 
- 그래서 해당 유틸 클래스를 사용해서 테스트 픽스쳐의 id값을 할당했습니다.
- 엔티티 클래스에서 `@NoArgsConstructor(Access = 'protected')` 어노테이션을 제거하였습니다.
- 어노테이션이 너무 많이붙어있는게 지저분하기도 했고
- 자바 코드로도 한 줄로 축약이 되어서, 롬복 어노테이션에 의존하기 보다는 그냥 자바 코드로 protected 생성자를 만들어 주는 것이 낫다고 판단하였습니다.

엔티티 클래스에서 @AllArgsConstructor 제거하기

---

backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageThumbnailDTO.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydsl.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
backend/src/main/java/com/daily/daily/post/controller/PostController.java
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java

close: #216 
- 다일리 생성 API 엔드포인트를 수정 (`/api/pages` -> `/api/dailry/{dailryID}/pages`)
- API응답 파라미터 `dailryPageId` -> `pageId`로 변경
-  다일리 페이지 생성 응답값에 `dailryId` 추가
-  다일리 썸네일 미리보기 응답값에 `pageId` 추가
- `DailryPageRepository` 에서 썸네일을 가져오는 메서드를 Querydsl로 변경했습니다. 
- 이유는 projection 대상으로 `pageId`까지 추가되니까 스프링 데이터 JPA의 쿼리메소드 기능으로는 버겁더라구요.
- 해당 인터페이스는 `List<DailryPageThumbnailDTO> findThumbnails(Long dailryId);` 입니다.

다일리 페이지 관련 리팩토링

---

backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java

x
서브모듈을 업데이트 했습니다.
도메인 이름 설정할 때 특수문자가 사용되면 안되네요
https://da-ily.site -> da-ily.site 로 변경했습니다.
+) restdocs 이미지 파일 관련 제한사항 docs 수정했습니다.

깃 서브모듈 업데이트(도메인 변수 재설정)

---

frontend/src/hooks/useModifyDecorateComponent.jsx
frontend/src/hooks/useNewDecorateComponent/useCompleteCreation.jsx
frontend/src/hooks/useNewDecorateComponent/useNewDecorateComponent.jsx
frontend/src/hooks/useSetTypeContent.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #223 
- 새로운 꾸미기 컴포넌트 생성 완료 커스텀 훅 추가
- useCompleteCreation
- isOtherActionTriggered 상태
- 다른 액션이 실행될 때, 해당 상태를 업데이트 하여, 생성이 완료되었다면 꾸미기 컴포넌트 배열에 추가, 그렇지 않다면 삭제
- 기존 useNewDecorateComponent 내부에 있던 생성 여부를 확인 하는 isCreationCompleted 이동
- 상위 컴포넌트에서 실행되던 addNewDecorateComponent 함수 이동
- 꾸미기 컴포넌트 수정 커스텀 훅 추가
- useModifyDecorateComponent
- 상위 컴포넌트에서 실행되던 modifyDecorateComponentTypeContent 함수 이동
- 상위 컴포넌트에 있던 canEditDecorateComponent 상태 이동
- 꾸미기 컴포넌트 내용 편집 커스텀 훅 추가
- useSetTypeContent
- 생성/수정 에 따라 새로운 꾸미기 컴포넌트/기존 꾸미기 컴포넌트 의 내용 편집 하는 기능

꾸미기 컴포넌트 내용 편집 리팩터링

---

frontend/package.json
frontend/src/index.js
frontend/src/pages/DailryPage/DailryPage.jsx

close: #229
`react-toastify`를 사용해 다일리 페이지 넘길 때 처음과 끝에서 메세지 띄움
```JavaScript
// react-toastify 사용법
// 1. import
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// 2. toast 함수 정의
const toastify = () => {
toast('토스트 메세지', {
position: 'bottom-right',
autoClose: 300,
});
};
// 3. 이벤트 달기
<button onClick={toastify} />
// 4. ToastContainer 렌더링. index.js에 한번만 넣으면 어디서나 사용가능하므로 따로 추가하지 않아도 됨
return <ToastContainer />
```

react-toastify 사용

---

frontend/src/components/decorate/DecorateWrapper.jsx
frontend/src/hooks/useNewDecorateComponent/properties.js
frontend/src/hooks/useNewDecorateComponent/useCompleteCreation.jsx
frontend/src/hooks/useNewDecorateComponent/useNewDecorateComponent.jsx
frontend/src/pages/DailryPage/DailryPage.jsx
frontend/src/pages/DailryPage/DailryPage.styled.jsx

close: #234 
* 새로운 꾸미기 컴포넌트 생성 시 순서, 각도 초기 값 지정
- `순서` : `꾸미기 컴포넌트 배열` 의 길이 를 순서로 지정
- `각도` : `'0deg'`
* `useNewDecorateComponent` 커스텀 훅 수정
- `initializeNewDecorateComponent` -> `removeNewDecorateComponent`
- 새로운 꾸미기 컴포넌트를 삭제하는 의미에서 더 적합하여 수정
* `newDecorateComponent` 초기값 `null` 로 수정

새로운 꾸미기 컴포넌트 생성 시 순서, 각도 초기 값 지정

---

backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java

close: #245 
**[local, dev] 환경**
```java
configuration.setAllowedOrigins(List.of("http://localhost:3000", "https://localhost:3000", "https://da-ily.site"));
```
**[prod] 환경**
```java
...
configuration.setAllowedOrigins(List.of("https://dailry.co.kr"));
configuration.setMaxAge(1800L); // preflight 요청을 30분 동안 캐싱. 불필요한 preflight 요청 감소
...
```
cors 요청을 보낼 때에는 클라이언트와 서버가 서로 요청을 주고 받아도 되는지 확인하기 위해
실제 요청 이전에 클라이언트 측에서 preflight 요청을 먼저 보냅니다.
그런데 `configuration.setMaxAge(1800L);` 설정을 하지 않으면 매번 서버에 요청할 때 마다 preflight 요청을 보내는 것 같네요
`configuration.setMaxAge(설정시간)` 메서드는 preflight 요청을 설정 시간 동안 브라우저에 캐싱하도록 한다고 합니다.
브라우저는 캐싱되어있는 preflight 요청이 있으면 그 다음부턴 preflight 요청을 보내지 않고, 바로 실제 요청을 보내는 것 같아요

CorsConfig 에서 Profile 별로 설정 빈을 다르게 등록하기

---

.github/workflows/backend-ci.yml
.github/workflows/backend-dev-cicd.yml
.github/workflows/backend-prod-cicd.yml
backend/src/main/java/com/daily/daily/common/service/CookieService.java

close: #248 
- PR이 올라왔을 때, PR이 올라온 브랜치가 제대로 Build 되는지 검증하는 CI 스크립트 작성
작성한 이유는 이슈 참고.
추가로 한일
- 모든 백엔드 workflow를 GithubAction Runner 환경에서 mysql 이미지를 띄운 다음에 빌드하도록 변경
- 이유는 jpa ddl-auto : validate 기능을 쓰기 위함. 
- h2 db를 mysql-mode로 사용해도, ddl-auto : validate가 작동하지 않음.
- 쿠키 sameSite value를 default 값을 Strict로 설정.
- 서브모듈에 환경별로 쿠키 설정을 기입

백엔드 Github Action CI 전용 스크립트 생성

---

backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
backend/src/test/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImplTest.java
backend/src/test/java/com/daily/daily/member/repository/MemberRepositoryTest.java
backend/src/test/java/com/daily/daily/post/repository/PostLikeRepositoryTest.java
backend/src/test/java/com/daily/daily/postcomment/repository/PostCommentRepositoryTest.java
backend/src/test/java/com/daily/daily/testutil/config/JpaTest.java
backend/src/test/java/com/daily/daily/testutil/generator/DailryGenerator.java
backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java

close: #255 
- 다일리 페이지 미리보기 버그 수정
- 테스트코드 작성
- 테스트코드 리팩토링
- DB를 사용하는 테스트의 경우 데이터를 삽입하는 코드가 중복될 여지가 있을 것 같아서
TestUtil에 Generator 클래스를 만들어서 데이터를 넣어주는 코드를 작성하였습니다.
- @DataJpaTest를 작성할 경우 빈 Import 때문에 코드 중복이 발생해서,
JpaTest 클래스에서 설정을 해주고 기존 @DataJpaTest 를 쓰던 클래스들은 JpaTest를 상속받도록 하였습니다.

다일리 페이지 미리보기 버그 수정하기

---

backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydsl.java
backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
backend/src/main/java/com/daily/daily/post/service/PostService.java
backend/src/test/java/com/daily/daily/post/repository/PostRepositoryTest.java
backend/src/test/java/com/daily/daily/testutil/config/JpaTest.java
backend/src/test/java/com/daily/daily/testutil/generator/HashtagGenerator.java
backend/src/test/java/com/daily/daily/testutil/generator/PostCommentGenerator.java
backend/src/test/java/com/daily/daily/testutil/generator/PostLikeGenerator.java

close: #259 
- 페이지 생성 api에서 pageNumber 값으로 null으로 오는 버그 수정
- DB에는 잘 반영이 되는데 응답 DTO에 pageNumber를 넣어주는 코드가 누락됨
- 다일리 DELETE 가 안되는 버그 수정
- 외래키 제약조건 때문에, 다일리 페이지를 모두 DELETE 해야 DELETE가 가능함.
- 비슷하게 게시글도 같은 이유로 DELETE가 안되는 상황이어서, 해당 부분을 수정하고 테스트코드를 작성함.
- Refresh 토큰 로직을 작성하기 전까지 임시로 dev환경의 액세스토큰 만료 시간을 늘림.

페이지 생성 API 버그 수정 / 다일리 DELETE 버그 수정 

---

frontend/src/apis/dailryApi.js
frontend/src/constants/toolbar.js
frontend/src/hooks/useNewDecorateComponent/properties.js
frontend/src/hooks/usePageData.jsx
frontend/src/pages/DailryPage/DailryPage.jsx
frontend/src/pages/DailryPage/DailryPage.styled.jsx

close: #262 
* 다일리 페이지 수정 API `patchPage` 함수 추가
* `usePageData` 커스텀 훅 추가
- `multipart/form-data` 형식의 데이터로 변환하는 `convertDecorateComponentsToBlob` 함수 추가
- 썸네일 데이터 에 해당하는 `thumbnail` 상태 추가
* `PAGE_TOOLS` 상수에 save 타입 추가
- 해당 타입 버튼 클릭 시 수정 API 호출 하도록 조건 추가
* 꾸미기 컴포넌트 공통 속성 중 size 타입 변경
* 꾸미기 컴포넌트 공통 속성 rotation 초기 값 수정

다일리 페이지 수정 API 연동

---

frontend/src/components/common/Navigation/DailryNavigation.jsx
frontend/src/components/decorate/Drawing/useDrawInstance.jsx
frontend/src/components/decorate/TextBox/TextBox.jsx
frontend/src/hooks/useDebounce.jsx
frontend/src/hooks/useDecorateComponents.jsx
frontend/src/hooks/useNewDecorateComponent/properties.js
frontend/src/hooks/useUpdatedDecorateComponents.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #267 
* 다일리 페이지 단건 조회 API 연동
* `DailryNavigation` 에서 `pageNumber` 를 제어하지 않도록 수정  
* 첫 렌더링 시 에만 `getPages` 호출하도록 수정
* `pageNumber` 값이 변경될 때, `getPage` 호출하도록 수정 `useEffect` 의존값 설정
- `pageNumber` 를 `pageIds` 의 인덱스로 `pageId` 검색 하여 호출 파라미터로 전송
* 꾸미기 컴포넌트 데이터 관련 버그 수정, 개선
- 공통속성 rotation 초기 값 수정
- `updatedDecorateComponents` 배열에 해당 꾸미기 컴포넌트가 있으면 수정, 없으면 삽입 하도록 수정
- TextBox 입력 데이터 와 typeContent 에 삽입할 데이터 분리
- `text` 라는 상태 추가 하여, `onChange` 이벤트가 실행될때 해당 상태의 값 갱신 하고, 일정시간 이후 `typeContent` 값 을 삽입하는 함수를 호출
* 클라이언트 에서 `pageNumber` 가 고유한 값으로 지속될 수 있는지, 확인 필요

다일리 페이지 단건 조회 API 연동 및 꾸미기 컴포넌트 데이터 관련 버그 수정, 개선

---

backend/src/docs/asciidoc/api-document.adoc
backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
backend/src/main/java/com/daily/daily/common/config/Business/BusinessConfig.java
backend/src/main/java/com/daily/daily/common/config/BusinessConfig.java
backend/src/main/java/com/daily/daily/post/controller/HotPostController.java
backend/src/main/java/com/daily/daily/post/domain/HotPost.java
backend/src/main/java/com/daily/daily/post/domain/Post.java
backend/src/main/java/com/daily/daily/post/dto/HotPostReadResponseDTO.java
backend/src/main/java/com/daily/daily/post/dto/HotPostReadSliceResponseDTO.java
backend/src/main/java/com/daily/daily/post/dto/PostReadSliceResponseDTO.java
backend/src/main/java/com/daily/daily/post/repository/HotPostRepository.java
backend/src/main/java/com/daily/daily/post/repository/HotPostRepositoryQuerydsl.java
backend/src/main/java/com/daily/daily/post/repository/HotPostRepositoryQuerydslImpl.java
backend/src/main/java/com/daily/daily/post/repository/PostLikeRepository.java
backend/src/main/java/com/daily/daily/post/service/HotPostService.java
backend/src/main/java/com/daily/daily/post/service/PostLikeFacade.java
backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
backend/src/main/resources/db/migration/V202403041352__addHotPostTable.sql
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/post/controller/HotPostControllerTest.java
backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
backend/src/test/java/com/daily/daily/post/fixture/HotPostFixture.java
backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
backend/src/test/java/com/daily/daily/post/service/PostLikeServiceConcurrencyTest.java
backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java

close: #263 
- DB 스키마 수정
- hot_post 테이블 추가
- post 테이블에 is_hot_post 컬럼 추가 (type : boolean)
- 좋아요를 많이 받은 인기 다일리 페이지 게시글(이하 인기글)을 별도로 조회할 수 있다.
- 최근 7일 동안 올라온 글 중에서 좋아요 갯수가 15이상이 되면 인기글이 된다.
- common/config/business 패키지에  BusinessConfig 클래스를 만들었습니다.
- 비즈니스 관련된 설정들을 여기에서 하면 좋을 것 같습니다. (ex : 인기 게시글로 올라가는 좋아요 기준치 등) 
- 굳이 따로 분리해서 비즈니스 로직에 관한 상수 클래스를 만든 이유는 비즈니스 설정을 변경하였을 때,
테스트코드가 깨지는 것을 방지하기 위해서 입니다.
테스트코드 에서도 매직 넘버가 아닌, 해당 상수를 쓰도록 하는 것이 변경에 더 수월할 것 같습니다.

인기 다일리 페이지 게시글 기능 추가

---

backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydsl.java
backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
backend/src/test/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImplTest.java
backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java

close: #274 
-  페이지를 삭제시, 해당 페이지 이후의 pageNumber를 1씩당기는 로직을 추가
음 일단 삭제되는 페이지의 pageNumber 보다 큰 페이지를 -1 하도록
업데이트 쿼리를 날려서 해결을 했는데요.. 
(delete 쿼리 하나, 벌크성 update 쿼리 하나, 두 개 나갑니다.)
이 방법이 최선인지는 잘 모르겠네요. 
가장 큰 문제는 pageNumber의 무결성이 한 번 깨지면 대처가 안된다는 점인데요.. 
(ex : 잘못해서 페이지 삭제 API가 순간적으로 두 번 호출된다면? 모든 pageNumber가 다 깨지게 됨.)
이 부분은 조금 의논을 해봐야 할 것 같습니다.

다일리 페이지 삭제 버그 수정

---

backend/src/main/java/com/daily/daily/common/domain/DirectoryPath.java
backend/src/main/java/com/daily/daily/common/exception/InvalidDirectoryException.java
backend/src/main/java/com/daily/daily/common/service/S3StorageService.java
backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
backend/src/main/java/com/daily/daily/post/service/PostService.java
backend/src/main/resources/static/docs/api-document.html
backend/src/test/java/com/daily/daily/common/file_save/DirectoryPathTest.java
backend/src/test/java/com/daily/daily/common/service/S3StorageServiceTest.java
backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
backend/src/test/java/com/daily/daily/dailrypage/service/DailryPageServiceTest.java
backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java

close: #276 
- dailryPageRequest에 deletedElementIds 필드 추가
- deletedElementIds의 id로 들어온 컴포넌트는 삭제한다.
**[ 리팩토링 ]**
- 다일리 페이지 썸네일 파일의 저장 경로를 바꾸었습니다.
- thumbnail/{memberId}/{dailryId}/{pageId}.png 
- 변경한 이유는 파일 경로나 이름에 시간 정보나 UUID가 있으면 썸네일 파일이 너무 많이 생길 것이 우려되어서 입니다.
- 위와 같은 경로로 설정하면 덮어쓰기 방식으로 이미지를 저장하기 때문에 이미지 파일이 덜 생성됩니다.
- S3StorageService 를 리팩토링 하였습니다.
- 클라이언트 코드에서 파일 이름을 지정할 수 있도록 하였습니다.
- 기존 코드는 S3StorageService에서 파일의 네이밍에 관여하였기에 유연하게 네이밍 전략을 짤 수 없었습니다.
-  디렉토리 경로를 다루는 객체 DirectoryPath 를 추가하였습니다.
- uploadImage() 메서드는 이제 String이 아니라 URI 객체를 반환하도록 하였습니다.

다일리 페이지 수정 API 꾸미기 컴포넌트 삭제 기능 반영하기 / S3 Storage 리팩토링

---

frontend/src/components/da-ily/Moveable/Moveable.jsx
frontend/src/components/decorate/DecorateWrapper.jsx
frontend/src/components/decorate/TextBox/TextBox.jsx
frontend/src/hooks/useEditDecorateComponent.jsx
frontend/src/hooks/useNewDecorateComponent/createNewDecorateComponent.jsx
frontend/src/hooks/useNewDecorateComponent/properties.js
frontend/src/pages/DailryPage/DailryPage.jsx
frontend/src/pages/DailryPage/DailryPage.styled.jsx

close: #271 
- `Moveable` 컴포넌트 과 타겟 꾸미기 컴포넌트 스타일 동기화 방식 변경
- `Moveable` 타겟이 변경될 때, 타겟의 스타일이 초기화 되지 않도록 수정
- `on~~~Start`, `on~~~End` 메서드 제거 (타겟의 스타일이 초기화 되는 원인)
- `onRender` 메서드 를 이용해 타겟 꾸미기 컴포넌트 스타일 을 동기화
- 서버에서 가져오는 `공통 속성` 과 실제 `Moveable` 컴포넌트의 메서드로 인해 바뀌는 꾸미기 컴포넌트 의 `공통 속성` 을 분리 
- `initialStyle`
- 서버에서 가져오는 `공통 속성`.
- 다일리 페이지 데이터를 fetch 할 때, 각 꾸미기 컴포넌트의 `공통 속성` 을 해당 속성에 할당하는 프로세스 추가
- `position`, `size`, `rotation`
- 기존 공통 속성 에 속하던 속성 그대로 사용.
- 실제 `Moveable` 컴포넌트 의 타겟 이 되어 바뀌는 값은 이 값들.
- 현재 꾸미기 컴포넌트의 공통 속성 이 서버에서 오는 것과 클라이언트에서 조정하는 것이 나누어져 있는데, 통합하거나 효과적으로 분리하는 것이 나을 것 같습니다.

꾸미기 컴포넌트 추가, 수정 기능 버그 픽스 및 개선

---

frontend/src/components/decorate/DeleteButton/DeleteButton.styled.jsx
frontend/src/hooks/usePageData.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #284 
* 삭제 버튼 추가
- `DeleteButton.styled.jsx`
* 삭제 시, 꾸미기 컴포넌트 `Id` 를 `삭제 Id 리스트` 에 추가, 클라이언트 에서 보여지는 꾸미기 컴포넌트 배열에서 제외
* 페이지 수정 시, 요청 Body 에 삭제 `Id 리스트` 포함
* 삭제 버튼 UI

꾸미기 컴포넌트 삭제

---

frontend/src/components/decorate/DeleteButton/DeleteButton.styled.jsx
frontend/src/hooks/usePageData.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

close: #281 
* `appendPageDataToFormData`
- 기존 `getPageFormData` 함수명 변경
- `페이지 수정 API` 호출 Body 에 들어갈 FormData 에 썸네일 포함
* 페이지 이미지 를 blob 으로 변환하는 toBlob 함수의 콜백함수 에서 페이지 수정 API 를 호출하도록 수정

페이지 수정 시, 페이지 썸네일 전송

---

frontend/src/hooks/useUpdatedDecorateComponents.jsx
frontend/src/pages/DailryPage/DailryPage.jsx

* save 타입 버튼 클릭 시, `Moveable` 타겟 없어지도록 수정
* 수정 가능한 꾸미기 컴포넌트 조건 수정, 삭제 버튼 생성 조건 수정
* 수정된 페이지 데이터를 저장하지 않고 페이지 이동 혹은 추가 했을 시, 프로세스 추가
- 꾸미기 컴포넌트 생성 혹은 수정 을 진행하던 도중, 페이지 이동 혹은 추가 을 시도할 시, 생성 혹은 수정을 완성하고 페이지 이동 혹은 추가 액션은 취소
- 추가 혹은 수정된 꾸미기 컴포넌트 가 있지만 저장하지 않고, 페이지 이동 혹은 추가 를 시도할 시, 저장을 물어보는 `confirm` 창을 띄우고 확인 시, 페이지 저장, 취소 시 `updatedDecorateComponents` 비열을 비우고 페이지 이동 혹은 추가.
- 꾸미기 컴포넌트 저장 조건

다일리 페이지 관련 버그 수정
